export const FOOTBALL_QUOTES = [
  "Se o jogo tá difícil, é porque o adversário tá jogando.", 
  "O importante é competir? Não, o importante é ganhar!",
  "O dia que eu não jogar bem, eu paro. Ou melhor, eu treino mais.",
  "Eu não sou craque, eu sou um jogador que faz gol... e não é pouco!",
  "Futebol é uma caixinha de surpresas... e a minha tá cheia de gol.",
  "Quem tem limite é município, craque tem é talento!",
  "Drible é uma arte, gol é uma necessidade, e celebrar é obrigação.",
  "A bola não entra por acaso, ela entra porque eu mandei.",
  "Não existe jogo ganho, existe jogo que a gente ainda não venceu.",
  "Futebol é simples, o difícil é jogar simples.",
  "Vocês vão ter que me engolir!",
  "Não sou desequilibrado, sou apenas intensamente apaixonado pelo futebol.",
  "O talento te leva longe, mas a disciplina te mantém lá.",
  "A bola é minha melhor amiga, ela nunca me deixa na mão.",
  "Jogar futebol é como viver: é preciso ter jogo de cintura.",
  "O jogo foi GG - joinha joinha.",
  "Clássico é clássico e vice-versa",
  "O meu coração só bate por um clube: o que estiver pagando o meu salário.",
  "Deus abençoe os secadores.",
  "Não sou o melhor do mundo, mas sou melhor que muitos que se acham.",
  "Para mim, fazer gol é como respirar.",
  "Tanto na minha vida profissional quanto na minha vida privada, eu sempre fui de frente. Nunca fui de trás.",
  "Não foi nada de grave, foi apenas uma dor de cabeça no tornozelo.",
  "O difícil, como vocês sabem, não é fácil.",
  "No futebol atual, a velocidade é fundamental. Tanto que, se o jogador correr muito rápido, ele chega antes da bola.",
  "Se o escorpião picar o meu calcanhar, ele morre envenenado.",
  "O jogador brasileiro é o único que joga para trás para depois ir para a frente... e se não der, ele cruza.",
  "Chora agora para rir depois.",
  "Eu não corro atrás da bola, a bola vem até mim.",
  "A bola ia entrando, ia entrando, ia entrando... e fuba, não entrou!",
  "O meu clube estava na beira do abismo, mas tomou a decisão certa: deu um passo à frente.",
  "Jogador de futebol tem que ser que nem jacaré: a lagoa tá seca, mas ele tá lá, esperando a água voltar.",
  "Não foi uma jogada ensaiada, foi uma jogada que aconteceu na hora porque a gente treinou muito.",
  "Não existe gol feio, feio é não fazer gol.",
  "Se o futebol é uma religião, eu sou o Papa.",
  "A bola é um instrumento de alegria. Quando ela está no meu pé, o mundo fica mais bonito.",
  "Quem não tem coragem de arriscar, não merece vencer.",
  "Eu tive uma torção no adutor da mente.",
  "As pessoas querem que o Brasil jogue o futebol do futuro, mas esquecem que o futuro ainda não chegou.",
  "O meu gol mais bonito foi de canela, porque a bola foi exatamente onde eu não queria que ela fosse.",
  "De degrau em degrau, a gente vai chegando ao topo da escada.",
  "Tratem bem a bola. Ela é uma senhora e só aceita ser acariciada.",
  "A bola não é uma inimiga que você chuta, é uma amiga que você conduz.",
  "Para mim, jogar futebol é desenhar no espaço.",
  "Só existem três coisas que param no ar: o beija-flor, o helicóptero e o Dadá Maravilha.",
  "Eu não preciso de um GPS para achar o gol. O gol me chama pelo nome.",
  "O novo técnico quer que a gente jogue pelas pontas, tanto pela esquerda quanto pela direita, ou seja, em todas as três pontas do campo.",
  "Eu fiz o gol de cabeça porque a bola veio na altura exata da minha testa.",
  "Não tem problema que o jogo seja na altitude, o importante é que a bola corre igual.",
  "A minha perna esquerda é cega, mas a direita enxerga muito bem.",
  "Treino é treino, jogo é jogo.",
  "Garrincha, você já combinou essa jogada com os russos?",
  "Eu não sou herói. Herói é quem trabalha de segunda a sábado para sustentar a família com um salário mínimo.",
  "Quem tem calcanhar de Aquiles é o Aquiles. O meu calcanhar é de ouro.",
  "A trave é o melhor amigo do goleiro, mas às vezes ela te trai e joga a bola para dentro.",
  "Quem aliveia é papai e mamãe!"
];
